version: '3'

services:
  flare-node-songbird:
    image: dulee/flare-node:songbird
    container_name: flare_node_songbird
    hostname: flare_node_songbird
    # restart: unless-stopped
    restart: on-failure
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 29650:9650
      - 29651:9651
      # - 9650:9650
      # - 9651:9651
    # Environment Variables in the Container
    environment:
      - FLARE_NETWORK_ID=${FLARE_NETWORK_ID:-songbird}
      # - HTTP_HOST=${HTTP_HOST:-0.0.0.0}
      - LISTEN_ADDRESS=0.0.0.0
      - BOOTSTRAP_IPS=${BOOTSTRAP_IPS:-}
      - BOOTSTRAP_IDS=${BOOTSTRAP_IDS:-}
      - DB_DIR=/db
      - LOG_DIR=/logs
      - CHAIN_CONFIG_DIR=${CHAIN_CONFIG_DIR:-/app/.flare/configs}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}    
    build:
      context: build
      dockerfile: Dockerfile.songbird
    # Env Variable from outside the container, i.e. SHELL Variables
    env_file:
      - ./build/.env.songbird
    volumes:
      - ${DB_DIR:-./db}:/db
      - ${LOG_DIR:-./logs}/logs:/logs
      - ${PWD}/configs:/app/.flare/configs