version: '3'

services:
  flare-node-coston:
    image: dulee/flare-node:coston
    container_name: flare_node_coston
    hostname: flare_node_coston
    # restart: unless-stopped
    restart: on-failure
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 19650:9650
      - 19651:9651
    environment:
      - FLARE_NETWORK_ID=${FLARE_NETWORK_ID:-coston}
      # - HTTP_HOST=${HTTP_HOST:-0.0.0.0}
      - LISTEN_ADDRESS=0.0.0.0
      - BOOTSTRAP_IPS=${BOOTSTRAP_IPS:-}
      - BOOTSTRAP_IDS=${BOOTSTRAP_IDS:-}
      - DB_DIR=${DB_DIR:-/db}
      - LOG_DIR=${LOG_DIR:-/logs}
      - CHAIN_CONFIG_DIR=${CHAIN_CONFIG_DIR:-/app/.flare/configs}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    build:
      context: build
      dockerfile: Dockerfile.coston
    env_file:
      - ./build/.env.coston
    volumes:
      - ${PWD}/db:/db
      - ${PWD}/logs:/logs
      - ${PWD}/configs/coston:/app/.flare/configs